name = "402-earth-payment-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true

[vars]
SITE_URL = "https://402.earth"
API_PUBLIC_URL = "https://api.402.earth"

[[d1_databases]]
binding = "DB"
database_name = "402-earth-payments"
database_id = "91f00944-0193-4412-9df8-f5c00b150d19"
migrations_dir = "migrations"

[[routes]]
pattern = "api.402.earth/*"
zone_name = "402.earth"
